### ISSUE TITLE
Broken images on some pages (links to root directory rather than assets)

### ISSUE THREAD

**Issue by rufuspollock** [life-itself/web3#219]
See e.g. https://web3.lifeitself.org/notes/emmett-2018-rewriting-story-human where images are broken

![image](https://user-images.githubusercontent.com/180658/234633235-361b8152-631b-429f-aeaa-89c6f26f106e.png)

**Comment by rufuspollock** [comment]
@khalilcodes could you take a quick look to see what's causing this i.e. < 15m or so. (not necessarily fix if that is painful or if you can't work out the issue)

**Comment by khalilcodes** [comment]
@rufuspollock this is happering because there is no assets folder within `site/content` (it's at root). The repo uses the old https://github.com/flowershow/remark-wiki-link-plus package and it searches for images within the `content` folder. 

A quick fix is symlinking the `assets` folder into `site/content`.

**Comment by rufuspollock** [comment]
@khalilcodes ok can you do that quick fix. Also can you open an issue about updating to Flowershow (and then we can estimate that).

**Comment by rufuspollock** [comment]
FIXED.
